# Generated by Django 4.2.2 on 2023-06-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_futbolista_fecha_nacimiento'),
        ('inicio', '0004_hockista'),
    ]

    operations = [
    ]
