# Generated by Django 4.2.2 on 2023-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_merge_20230624_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voleibolista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
