# Generated by Django 4.2.3 on 2023-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_voleibolista_alter_futbolista_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
