# Generated by Django 4.2.3 on 2023-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_infoextra_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='biografia',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='facebook',
            field=models.URLField(null=True),
        ),
    ]
