# Generated by Django 4.2.3 on 2023-07-15 18:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('destinatario', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
    ]
